#!/usr/bin/env sh

if [ -d ${HOME}/.cache/dein ]
then
  echo "[SKIP] dein is already installed"
else
  curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
  sh ./installer.sh ${HOME}/.cache/dein
  echo "[INST] dein is installed"
fi


