#!/usr/bin/env sh

if [ -d ${HOME}/.rbenv ]
then
  echo "[SKIP] rbenv is already installed"
else
  git clone https://github.com/rbenv/rbenv.git ~/.rbenv
  git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
  echo "[INST] rbenv is installed"
fi


