#!/usr/bin/env sh

if [ -d ${HOME}/.oh-my-zsh ]
then
  echo "[SKIP] oh-my-zsh is already installed"
else
  git clone https://github.com/ohmyzsh/ohmyzsh.git ${HOME}/.oh-my-zsh
  echo "[INST] oh-my-zsh is installed"
fi


