#!/bin/sh

if [ -d ${HOME}/.fonts/adobe-fonts/source-code-pro ]
then
  info "adobe-source-code-pro has already been installed"
else
  mkdir -p ${HOME}/.fonts/adobe-fonts/source-code-pro
  git clone https://github.com/adobe-fonts/source-code-pro.git ${HOME}/.fonts/adobe-fonts/source-code-pro
  fc-cache -f -v ${HOME}/.fonts/adobe-fonts/source-code-pro
  echo "finished installing"
fi
