#!/usr/bin/env sh

if [ -d ${HOME}/.tmux/plugins/tpm ]
then
  echo "[SKIP] tmux plugin manager is already installed"
else
  git clone https://github.com/tmux-plugins/tpm ${HOME}/.tmux/plugins/tpm
  echo "[INST] tmux-plugin-managerh is installed"
fi


