#!/usr/bin/env sh

if [ -d ${HOME}/.nodenv ]
then
  echo "[SKIP] nodenv is already installed"
else
  git clone https://github.com/nodenv/nodenv.git ~/.nodenv
  git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build
  echo "[INST] nodenv is installed"
fi


